### ISSUE TITLE
Adding simplifiers/focusers makes previously functional Op matches fail

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#188]
With an Op defined that takes a `double` param:
```
- op:
    names: [filter.gauss, cv.GaussianBlur]
    description: ''
    source: javaMethod:/org.bytedeco.opencv.global.opencv_imgproc.GaussianBlur%28org.bytedeco.opencv.opencv_core.Mat%2Corg.bytedeco.opencv.opencv_core.Mat%2Corg.bytedeco.opencv.opencv_core.Size%2Cdouble%29
    priority: 0.0
    version: '1'
    parameters:
    - {parameter type: INPUT, name: arg0, description: '', type: org.bytedeco.opencv.opencv_core.Mat}
    - {parameter type: CONTAINER, name: arg1, description: '', type: org.bytedeco.opencv.opencv_core.Mat}
    - {parameter type: INPUT, name: arg2, description: '', type: org.bytedeco.opencv.opencv_core.Size}
    - {parameter type: INPUT, name: arg3, description: '', type: double}
    authors: [OpenCV authors, bytedeco/JavaCV authors]
    tags: {type: Computer2}
```

I call it in a test adapting an `int` to the `double` with no problem:
```
int stDev = 100;
Size size = new Size(5, 5);
OpBuilder.Arity3_IV_OV<Mat, Size, Integer, Mat> builder = ops.ternary(TEST_OP).input(src, size, stDev).output(opsFish);
```

However, when I then add `Mat` focusers and simplifiers, e.g.:
```
- op:
    names: [engine.focus, cv.getUnsignedByteMat]
    description: ''
    source: javaMethod:/net.imagej.opencv.ImgToMatConverter.getUnsignedByteMat%28net.imglib2.RandomAccessibleInterval%29
    priority: 4.0
    version: '1'
    parameters:
    - {parameter type: INPUT, name: arg0, description: '', type: net.imglib2.RandomAccessibleInterval}
    authors: [Gabriella Turek]
    tags: {}
- op:
    names: [engine.simplify, cv.toByteImg]
    description: ''
    source: javaMethod:/net.imagej.opencv.MatToImgConverter.toByteImg%28org.bytedeco.opencv.opencv_core.Mat%29
    priority: 7.0
    version: '1'
    parameters:
    - {parameter type: INPUT, name: arg0, description: '', type: org.bytedeco.opencv.opencv_core.Mat}
    authors: [Gabriella Turek]
    tags: {}
```

The call no longer passes, with an exception:
```
No matching 'engine.copy/org.scijava.function.Computers.Arity1<org.bytedeco.opencv.opencv_core.Mat, org.bytedeco.opencv.opencv_core.Mat>' op
Request:
-	Name: "engine.copy", Types: org.scijava.function.Computers.Arity1<org.bytedeco.opencv.opencv_core.Mat, org.bytedeco.opencv.opencv_core.Mat>
Input Types: 
		* org.bytedeco.opencv.opencv_core.Mat
		* org.bytedeco.opencv.opencv_core.Mat
Output Type: 
		* org.bytedeco.opencv.opencv_core.Mat
```

But passes if I change the call to:
```
double stDev = 100.0;
Size size = new Size(5, 5);
OpBuilder.Arity3_IV_OV<Mat, Size, Double, Mat> builder = ops.ternary(TEST_OP).input(src, size, stDev).output(opsFish);
```

So it seems that there's some aggressive attempts at parameter simplification even when it is unnecessary?
