### ISSUE TITLE
SciJava Ops: create external configuration mechanism

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#97]
Javadoc discovery via therapi is great for dependency-free op registration, but still requires modification to "source" code. Ultimately for adoption we need a mechanism for registering ops without any changes to source or documentation.

It seems sensible to support a configuration file syntax, e.g. in yml.

This would likely be the mechanism for including libraries in other languages.

If a library has a mechanism for introspecting its available algorithms, we could (on a per-library basis) create an automated mechanism that generates a companion ops configuration yml, and it would also provide a path for manual configuration when introspection is not possible.

**Comment by gselzer** [comment]
Sure. What items are needed? Shall we prototype something like this?
```yml
info:
  source: Java
  package: ImageJ Ops2
  version: 0-SNAPSHOT

ops:
  - op:
      name: filter.gauss
      priority: 0.0
      source: net.imagej.ops2.filter.gauss.GaussRAI
      parameters:
        - input: in1
        - input: in2
        - container: out

```
